In [1]:
import pandas as pd
import ast

In [2]:
df_banglore = pd.read_excel("bangalore_cars.xlsx")

In [3]:
df_banglore.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1481 entries, 0 to 1480
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   new_car_detail    1481 non-null   object
 1   new_car_overview  1481 non-null   object
 2   new_car_feature   1481 non-null   object
 3   new_car_specs     1481 non-null   object
 4   car_links         1481 non-null   object
dtypes: object(5)
memory usage: 58.0+ KB

In [4]:
df_banglore

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1476,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1477,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1478,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1479,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1480,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [5]:
df_banglore.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1481 entries, 0 to 1480
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   new_car_detail    1481 non-null   object
 1   new_car_overview  1481 non-null   object
 2   new_car_feature   1481 non-null   object
 3   new_car_specs     1481 non-null   object
 4   car_links         1481 non-null   object
dtypes: object(5)
memory usage: 58.0+ KB

parse means converting a string (which looks like a dictionary or JSON) into an actual structured Python object, like a dictionary.
"{'fuel': 'Petrol', 'year': 2018}"  # This is a string
When you parse it using something like ast.literal_eval() or json.loads(), it becomes:
{'fuel': 'Petrol', 'year': 2018}  # Now it's a Python dictionary

Flatten means:
If that dictionary has nested data (like key-value pairs inside another dictionary), you “flatten” it by converting the nested structure into separate columns in a table.
{
  "user": {
    "id": 1,
    "info": {
      "name": "Rahul",
      "city": "Chennai"
    }
  }
}
from pandas import json_normalize

flat = json_normalize(data)
print(flat)
output:
{
  "user.id": 1,
  "user.info.name": "Rahul",
  "user.info.city": "Chennai"
}

In [6]:
# pd.set_option('display.max_colwidth', None)

In [7]:
def parse_json_column(json_string):
    return ast.literal_eval(json_string) # ast.literal_eval() is a function in Python that evaluates a string containing a Python literal expression and returns the corresponding Python object.

In [8]:
new_car_detail_b = df_banglore['new_car_detail'].apply(parse_json_column).apply(pd.Series)
new_car_overview_b = df_banglore['new_car_overview'].apply(parse_json_column).apply(pd.Series)

In [9]:
new_car_detail_b

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,3979,VXI,₹ 4 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,6087,1.5 Petrol Titanium BSIV,₹ 8.11 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,2983,1.2 Revotron XZ,₹ 5.85 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,1867,1.2 Kappa S Option,₹ 4.62 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,4277,DDiS 200 Zeta,₹ 7.90 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,0,Diesel,SUV,"1,56,039",Manual,2,2nd Owner,Toyota,Toyota Fortuner,2012,2253,4x4 MT,₹ 16.49 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1477,0,Petrol,Sedan,"56,000",Manual,2,2nd Owner,Maruti,Maruti SX4,2008,4257,Zxi BSIII,₹ 3.30 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1478,0,Petrol,Hatchback,"42,000",Manual,2,2nd Owner,Honda,Honda Brio,2014,1188,S MT,₹ 4.25 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1479,0,Diesel,Hatchback,"93,003",Manual,1,1st Owner,Hyundai,Hyundai i20,2018,5695,1.4 Asta Dual Tone,₹ 7.50 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1480,0,Petrol,Hatchback,"36,000",Automatic,2,2nd Owner,Hyundai,Hyundai Grand i10,2017,1523,Asta Option AT,₹ 6.75 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...

In [10]:
new_car_detail_b.drop(["it","ft","transmission","owner","centralVariantId","variantName","priceActual","priceSaving","priceFixedText","trendingText"],axis=1,inplace=True)

In [11]:
new_car_overview_b

,heading,top,bottomData
0,Car overview,"[{'key': 'Registration Year', 'value': '2015',...",None
1,Car overview,"[{'key': 'Registration Year', 'value': 'Feb 20...",None
2,Car overview,"[{'key': 'Registration Year', 'value': 'Sept 2...",None
3,Car overview,"[{'key': 'Registration Year', 'value': 'Dec 20...",None
4,Car overview,"[{'key': 'Registration Year', 'value': '2015',...",None
...,...,...,...
1476,Car overview,"[{'key': 'Registration Year', 'value': 'May 20...",None
1477,Car overview,"[{'key': 'Registration Year', 'value': 'Jun 20...",None
1478,Car overview,"[{'key': 'Registration Year', 'value': 'Sept 2...",None
1479,Car overview,"[{'key': 'Registration Year', 'value': 'Dec 20...",None
1480,Car overview,"[{'key': 'Registration Year', 'value': 'May 20...",None

In [12]:
new_car_overview_b['top'] = new_car_overview_b['top'].apply(lambda lst: {d['key']: d['value'] for d in lst})
new_car_overview_b = new_car_overview_b['top'].tolist()
new_car_overview_b = pd.DataFrame(new_car_overview_b)

In [13]:
new_car_overview_b

,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,RTO,Ownership,Engine Displacement,Transmission,Year of Manufacture
0,2015,Third Party insurance,Petrol,5 Seats,"1,20,000 Kms",KA51,Third Owner,998 cc,Manual,2015.0
1,Feb 2018,Comprehensive,Petrol,5 Seats,"32,706 Kms",KA05,Second Owner,1497 cc,Manual,2018.0
2,Sept 2018,Comprehensive,Petrol,5 Seats,"11,949 Kms",KA03,First Owner,1199 cc,Manual,2018.0
3,Dec 2014,Comprehensive,Petrol,5 Seats,"17,794 Kms",KA53,First Owner,1197 cc,Manual,2014.0
4,2015,Third Party insurance,Diesel,5 Seats,"60,000 Kms",KA04,First Owner,1248 cc,Manual,2015.0
...,...,...,...,...,...,...,...,...,...,...
1476,May 2012,Comprehensive,Diesel,7 Seats,"1,56,039 Kms",KA01,Second Owner,2982 cc,Manual,2012.0
1477,Jun 2008,Third Party insurance,Petrol,5 Seats,"56,000 Kms",KA02,Second Owner,1586 cc,Manual,2008.0
1478,Sept 2014,Comprehensive,Petrol,5 Seats,"42,000 Kms",KA03,Second Owner,1198 cc,Manual,2014.0
1479,Dec 2018,Comprehensive,Diesel,5 Seats,"93,003 Kms",KA03,First Owner,1396 cc,Manual,2018.0
1480,May 2017,Comprehensive,Petrol,5 Seats,"36,000 Kms",KA04,Second Owner,1197 cc,Automatic,2017.0

In [14]:
new_car_overview_b.drop(["Registration Year","Insurance Validity","Kms Driven","RTO","Ownership","Engine Displacement","Transmission","Year of Manufacture"],axis=1,inplace= True)

In [15]:
banglore_df= pd.concat([new_car_detail_b,new_car_overview_b],axis =1)

In [16]:
banglore_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1481 entries, 0 to 1480
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   bt         1481 non-null   object
 1   km         1481 non-null   object
 2   ownerNo    1481 non-null   int64
 3   oem        1481 non-null   object
 4   model      1481 non-null   object
 5   modelYear  1481 non-null   int64
 6   price      1481 non-null   object
 7   Fuel Type  1481 non-null   object
 8   Seats      1480 non-null   object
dtypes: int64(2), object(7)
memory usage: 104.3+ KB

In [17]:
banglore_df["city"] = "Banglore"

In [18]:
banglore_df

,bt,km,ownerNo,oem,model,modelYear,price,Fuel Type,Seats,city
0,Hatchback,"1,20,000",3,Maruti,Maruti Celerio,2015,₹ 4 Lakh,Petrol,5 Seats,Banglore
1,SUV,"32,706",2,Ford,Ford Ecosport,2018,₹ 8.11 Lakh,Petrol,5 Seats,Banglore
2,Hatchback,"11,949",1,Tata,Tata Tiago,2018,₹ 5.85 Lakh,Petrol,5 Seats,Banglore
3,Sedan,"17,794",1,Hyundai,Hyundai Xcent,2014,₹ 4.62 Lakh,Petrol,5 Seats,Banglore
4,SUV,"60,000",1,Maruti,Maruti SX4 S Cross,2015,₹ 7.90 Lakh,Diesel,5 Seats,Banglore
...,...,...,...,...,...,...,...,...,...,...
1476,SUV,"1,56,039",2,Toyota,Toyota Fortuner,2012,₹ 16.49 Lakh,Diesel,7 Seats,Banglore
1477,Sedan,"56,000",2,Maruti,Maruti SX4,2008,₹ 3.30 Lakh,Petrol,5 Seats,Banglore
1478,Hatchback,"42,000",2,Honda,Honda Brio,2014,₹ 4.25 Lakh,Petrol,5 Seats,Banglore
1479,Hatchback,"93,003",1,Hyundai,Hyundai i20,2018,₹ 7.50 Lakh,Diesel,5 Seats,Banglore
1480,Hatchback,"36,000",2,Hyundai,Hyundai Grand i10,2017,₹ 6.75 Lakh,Petrol,5 Seats,Banglore

In [19]:
df_chennai = pd.read_excel("chennai_cars.xlsx")

In [20]:
df_chennai.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1419 entries, 0 to 1418
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   new_car_detail    1419 non-null   object
 1   new_car_overview  1419 non-null   object
 2   new_car_feature   1419 non-null   object
 3   new_car_specs     1419 non-null   object
 4   car_links         1419 non-null   object
dtypes: object(5)
memory usage: 55.6+ KB

In [21]:
new_car_detail_c = df_chennai['new_car_detail'].apply(parse_json_column).apply(pd.Series)
new_car_overview_c = df_chennai['new_car_overview'].apply(parse_json_column).apply(pd.Series)

In [22]:
new_car_detail_c.drop(["it","ft","transmission","owner","centralVariantId","variantName","priceActual","priceSaving","priceFixedText","trendingText"],axis=1,inplace=True)

In [23]:
new_car_overview_c['top'] = new_car_overview_c['top'].apply(lambda lst: {d['key']: d['value'] for d in lst})
new_car_overview_c = new_car_overview_c['top'].tolist()
new_car_overview_c = pd.DataFrame(new_car_overview_c)

In [24]:
new_car_overview_c.drop(["Registration Year","Insurance Validity","Kms Driven","RTO","Ownership","Engine Displacement","Transmission","Year of Manufacture"],axis=1,inplace= True)

In [25]:
chennai_df= pd.concat([new_car_detail_c,new_car_overview_c],axis =1)

In [26]:
chennai_df["city"] = "Chennai"

In [27]:
chennai_df

,bt,km,ownerNo,oem,model,modelYear,price,Fuel Type,Seats,city
0,SUV,"20,000",1,Kia,Kia Sonet,2022,₹ 11.50 Lakh,Petrol,5 Seats,Chennai
1,Minivans,"20,687",1,Maruti,Maruti Eeco,2015,₹ 4.15 Lakh,Petrol,7 Seats,Chennai
2,SUV,"30,000",1,Nissan,Nissan Magnite,2021,₹ 7.50 Lakh,Petrol,5 Seats,Chennai
3,Hatchback,"59,247",1,Hyundai,Hyundai i10,2015,₹ 3.98 Lakh,Petrol,5 Seats,Chennai
4,Hatchback,"50,000",1,Honda,Honda Jazz,2015,₹ 5.50 Lakh,Petrol,5 Seats,Chennai
...,...,...,...,...,...,...,...,...,...,...
1414,Hatchback,"42,891",1,Maruti,Maruti Swift,2018,₹ 6.20 Lakh,Petrol,5 Seats,Chennai
1415,SUV,"59,100",1,Renault,Renault Duster,2018,₹ 8.90 Lakh,Diesel,5 Seats,Chennai
1416,SUV,"55,913",1,Tata,Tata Nexon,2018,₹ 8.01 Lakh,Petrol,5 Seats,Chennai
1417,SUV,"65,000",1,Volkswagen,Volkswagen Tiguan,2017,₹ 20.50 Lakh,Diesel,5 Seats,Chennai
1418,Sedan,"60,000",1,BMW,BMW 3 Series GT,2019,₹ 35.75 Lakh,Diesel,5 Seats,Chennai

In [28]:
df_delhi = pd.read_excel("delhi_cars.xlsx")

In [29]:
df_delhi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1485 entries, 0 to 1484
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   new_car_detail    1485 non-null   object
 1   new_car_overview  1485 non-null   object
 2   new_car_feature   1485 non-null   object
 3   new_car_specs     1485 non-null   object
 4   car_links         1485 non-null   object
dtypes: object(5)
memory usage: 58.1+ KB

In [30]:
new_car_detail_d = df_delhi['new_car_detail'].apply(parse_json_column).apply(pd.Series)
new_car_overview_d = df_delhi['new_car_overview'].apply(parse_json_column).apply(pd.Series)

In [31]:
new_car_detail_d.drop(["it","ft","transmission","owner","centralVariantId","variantName","priceActual","priceSaving","priceFixedText","trendingText"],axis=1,inplace=True)

In [32]:
new_car_overview_d['top'] = new_car_overview_d['top'].apply(lambda lst: {d['key']: d['value'] for d in lst})
new_car_overview_d = new_car_overview_d['top'].tolist()
new_car_overview_d = pd.DataFrame(new_car_overview_d)

In [33]:
new_car_overview_d.drop(["Registration Year","Insurance Validity","Kms Driven","RTO","Ownership","Engine Displacement","Transmission","Year of Manufacture"],axis=1,inplace= True)

In [34]:
delhi_df= pd.concat([new_car_detail_d,new_car_overview_d],axis =1)

In [35]:
delhi_df["city"] = "Delhi"

In [36]:
delhi_df

,bt,km,ownerNo,oem,model,modelYear,price,Fuel Type,Seats,city
0,SUV,"10,000",1,Kia,Kia Seltos,2022,₹ 19 Lakh,Diesel,5 Seats,Delhi
1,SUV,"57,437",2,Hyundai,Hyundai Creta,2016,₹ 7.62 Lakh,Petrol,5 Seats,Delhi
2,SUV,"8,000",1,Mercedes-Benz,Mercedes-Benz GLC,2020,₹ 56 Lakh,Petrol,5 Seats,Delhi
3,Hatchback,"28,151",2,Maruti,Maruti Swift,2018,₹ 5.23 Lakh,Petrol,5 Seats,Delhi
4,SUV,"60,000",1,Hyundai,Hyundai Creta,2017,₹ 7.65 Lakh,Petrol,5 Seats,Delhi
...,...,...,...,...,...,...,...,...,...,...
1480,Sedan,"60,000",1,Honda,Honda City,2019,₹ 9 Lakh,Petrol,5 Seats,Delhi
1481,SUV,"20,000",1,Kia,Kia Sonet,2021,₹ 9.50 Lakh,Petrol,5 Seats,Delhi
1482,Sedan,"60,000",1,Hyundai,Hyundai Verna,2011,₹ 4.18 Lakh,Petrol,5 Seats,Delhi
1483,SUV,"38,000",1,Hyundai,Hyundai Creta,2019,₹ 11.95 Lakh,Diesel,5 Seats,Delhi
1484,SUV,"7,000",0,MG,MG Gloster,2023,₹ 46.40 Lakh,Diesel,6 Seats,Delhi

In [37]:
df_kolkata = pd.read_excel("kolkata_cars.xlsx")

In [38]:
df_kolkata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1381 entries, 0 to 1380
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   new_car_detail    1381 non-null   object
 1   new_car_overview  1381 non-null   object
 2   new_car_feature   1381 non-null   object
 3   new_car_specs     1381 non-null   object
 4   car_links         1381 non-null   object
dtypes: object(5)
memory usage: 54.1+ KB

In [39]:
new_car_detail_k = df_kolkata['new_car_detail'].apply(parse_json_column).apply(pd.Series)
new_car_overview_k = df_kolkata['new_car_overview'].apply(parse_json_column).apply(pd.Series)

In [40]:
new_car_detail_k.drop(["it","ft","transmission","owner","centralVariantId","variantName","priceActual","priceSaving","priceFixedText","trendingText"],axis=1,inplace=True)

In [41]:
new_car_overview_k['top'] = new_car_overview_k['top'].apply(lambda lst: {d['key']: d['value'] for d in lst})
new_car_overview_k = new_car_overview_k['top'].tolist()
new_car_overview_k = pd.DataFrame(new_car_overview_k)

In [42]:
new_car_overview_k.drop(["Registration Year","Insurance Validity","Kms Driven","RTO","Ownership","Engine Displacement","Transmission","Year of Manufacture"],axis=1,inplace= True)

In [43]:
Kolkata_df= pd.concat([new_car_detail_k,new_car_overview_k],axis =1)

In [44]:
Kolkata_df["city"] = "Kolkata"

In [45]:
Kolkata_df

,bt,km,ownerNo,oem,model,modelYear,price,Fuel Type,Seats,city
0,Sedan,"70,000",3,Toyota,Toyota Camry,2014,₹ 9.75 Lakh,Petrol,5 Seats,Kolkata
1,Hatchback,"23,981",1,Datsun,Datsun RediGO,2017,₹ 2.66 Lakh,Petrol,5 Seats,Kolkata
2,SUV,"7,100",1,Renault,Renault Kiger,2021,₹ 5.95 Lakh,Petrol,5 Seats,Kolkata
3,Hatchback,"71,574",2,Hyundai,Hyundai i20,2011,₹ 2.23 Lakh,Petrol,5 Seats,Kolkata
4,SUV,"50,000",2,Audi,Audi Q3,2014,₹ 12 Lakh,Diesel,5 Seats,Kolkata
...,...,...,...,...,...,...,...,...,...,...
1376,Hatchback,"10,000",1,Maruti,Maruti Celerio,2022,₹ 5.10 Lakh,Petrol,5 Seats,Kolkata
1377,Hatchback,"1,20,000",1,Maruti,Maruti Alto 800,2014,₹ 1.80 Lakh,Petrol,5 Seats,Kolkata
1378,Sedan,"50,000",3,Mercedes-Benz,Mercedes-Benz C-Class,2011,₹ 5.50 Lakh,Petrol,5 Seats,Kolkata
1379,Hatchback,"40,000",1,Maruti,Maruti Ritz,2012,₹ 1.40 Lakh,Petrol,5 Seats,Kolkata
1380,SUV,"1,20,000",2,Renault,Renault Duster,2017,₹ 5 Lakh,Diesel,5 Seats,Kolkata

In [46]:
df=pd.concat([banglore_df,chennai_df,delhi_df,Kolkata_df],axis=0, ignore_index=True)

In [47]:
df

,bt,km,ownerNo,oem,model,modelYear,price,Fuel Type,Seats,city
0,Hatchback,"1,20,000",3,Maruti,Maruti Celerio,2015,₹ 4 Lakh,Petrol,5 Seats,Banglore
1,SUV,"32,706",2,Ford,Ford Ecosport,2018,₹ 8.11 Lakh,Petrol,5 Seats,Banglore
2,Hatchback,"11,949",1,Tata,Tata Tiago,2018,₹ 5.85 Lakh,Petrol,5 Seats,Banglore
3,Sedan,"17,794",1,Hyundai,Hyundai Xcent,2014,₹ 4.62 Lakh,Petrol,5 Seats,Banglore
4,SUV,"60,000",1,Maruti,Maruti SX4 S Cross,2015,₹ 7.90 Lakh,Diesel,5 Seats,Banglore
...,...,...,...,...,...,...,...,...,...,...
5761,Hatchback,"10,000",1,Maruti,Maruti Celerio,2022,₹ 5.10 Lakh,Petrol,5 Seats,Kolkata
5762,Hatchback,"1,20,000",1,Maruti,Maruti Alto 800,2014,₹ 1.80 Lakh,Petrol,5 Seats,Kolkata
5763,Sedan,"50,000",3,Mercedes-Benz,Mercedes-Benz C-Class,2011,₹ 5.50 Lakh,Petrol,5 Seats,Kolkata
5764,Hatchback,"40,000",1,Maruti,Maruti Ritz,2012,₹ 1.40 Lakh,Petrol,5 Seats,Kolkata
5765,SUV,"1,20,000",2,Renault,Renault Duster,2017,₹ 5 Lakh,Diesel,5 Seats,Kolkata

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5766 entries, 0 to 5765
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   bt         5766 non-null   object
 1   km         5766 non-null   object
 2   ownerNo    5766 non-null   int64
 3   oem        5766 non-null   object
 4   model      5766 non-null   object
 5   modelYear  5766 non-null   int64
 6   price      5766 non-null   object
 7   Fuel Type  5766 non-null   object
 8   Seats      5761 non-null   object
 9   city       5766 non-null   object
dtypes: int64(2), object(8)
memory usage: 450.6+ KB

In [49]:
Column_names= ["Body_Type","Kilometers","Owners","Brand","Model","Model_Year","Price(Lakhs)","Fuel_Type","Seats","City"]

In [50]:
df.columns= Column_names

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5766 entries, 0 to 5765
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Body_Type     5766 non-null   object
 1   Kilometers    5766 non-null   object
 2   Owners        5766 non-null   int64
 3   Brand         5766 non-null   object
 4   Model         5766 non-null   object
 5   Model_Year    5766 non-null   int64
 6   Price(Lakhs)  5766 non-null   object
 7   Fuel_Type     5766 non-null   object
 8   Seats         5761 non-null   object
 9   City          5766 non-null   object
dtypes: int64(2), object(8)
memory usage: 450.6+ KB

In [52]:
df.dropna(inplace= True)

In [53]:
df["Kilometers"]= df["Kilometers"].str.replace(",", "").astype(int)

In [54]:
df["Seats"]= df["Seats"].str.replace("Seats", "").astype(int)

In [55]:
df["Price(Lakhs)"] = df["Price(Lakhs)"].str.replace("₹", "", regex=False)

In [56]:
def convert_price_to_lakhs(price_str):
    if "Crore" in price_str:
        return float(price_str.replace("Crore", "")) * 100
    elif "Lakh" in price_str:
        return float(price_str.replace("Lakh", ""))
    else:
        return None

In [57]:
df["Price(Lakhs)"] = df["Price(Lakhs)"].apply(convert_price_to_lakhs)

In [58]:
df.dropna(inplace=True)

In [59]:
df.to_csv("final.csv",index=False)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5706 entries, 0 to 5765
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Body_Type     5706 non-null   object
 1   Kilometers    5706 non-null   int64
 2   Owners        5706 non-null   int64
 3   Brand         5706 non-null   object
 4   Model         5706 non-null   object
 5   Model_Year    5706 non-null   int64
 6   Price(Lakhs)  5706 non-null   float64
 7   Fuel_Type     5706 non-null   object
 8   Seats         5706 non-null   int64
 9   City          5706 non-null   object
dtypes: float64(1), int64(4), object(5)
memory usage: 490.4+ KB